export interface CardData {
  id: string;
  template_id: string;
  sender: string;
  recipient: string;
  message: string;
  giphy_id: string;
  created_at?: string; // optional on insert, as it's auto-generated by supabase
}

export interface Template {
  id: string;
  name: string;
  description: string;
  image_url: string;
  preview_card_id: string;
}

export interface Gif {
  id: string;
  title: string;
  images: {
    fixed_height: {
      url: string;
    };
  };
}
