export interface CardData {
  id: string;
  template_id: string;
  sender: string;
  recipient: string;
  message: string;
  giphy_id: string;
  created_at?: string; // optional on insert, as it's auto-generated by supabase
}
